CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE skills (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    "Category" text,
    "Icon" text,
    "Popularity" integer,
    created_at timestamp without time zone DEFAULT (now()),
    CONSTRAINT "PK_skills" PRIMARY KEY (id)
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    email character varying(100) NOT NULL,
    "PasswordHash" bytea NOT NULL,
    "PasswordSalt" bytea NOT NULL,
    role character varying(20) NOT NULL DEFAULT 'user',
    status character varying(20) NOT NULL DEFAULT 'active',
    full_name character varying(100) NOT NULL,
    phone character varying(20),
    avatar character varying(255),
    about_me text,
    address character varying(255),
    birthday timestamp without time zone,
    gender character varying(10),
    job_title character varying(100),
    salary_expectation integer,
    cv_file character varying(255),
    created_at timestamp without time zone NOT NULL DEFAULT (now()),
    updated_at timestamp without time zone DEFAULT (now()),
    "BannedUntil" timestamp without time zone,
    "BanReason" text,
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE TABLE "AdminLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AdminId" integer NOT NULL,
    "Action" text,
    "TargetType" text,
    "TargetId" integer NOT NULL,
    "Reason" text,
    "Metadata" text,
    "CreatedAt" timestamp without time zone,
    CONSTRAINT "PK_AdminLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdminLogs_users_AdminId" FOREIGN KEY ("AdminId") REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE companies (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Name" text NOT NULL,
    "Logo" text,
    "Description" text,
    "Website" text,
    "Industry" text,
    "Size" text,
    "FoundedYear" integer,
    verification_status character varying(20) DEFAULT 'pending',
    created_at timestamp without time zone DEFAULT (now()),
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_companies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_companies_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE messages (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FromUserId" integer NOT NULL,
    "ToUserId" integer NOT NULL,
    "Message1" text NOT NULL,
    "Attachment" text,
    "IsRead" boolean,
    "CreatedAt" timestamp without time zone,
    CONSTRAINT "PK_messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_messages_users_FromUserId" FOREIGN KEY ("FromUserId") REFERENCES users (id),
    CONSTRAINT "FK_messages_users_ToUserId" FOREIGN KEY ("ToUserId") REFERENCES users (id)
);

CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Type" text,
    "Title" text,
    "Content" text,
    "Data" text,
    "IsRead" boolean,
    "CreatedAt" timestamp without time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE projects (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    type character varying(20) NOT NULL,
    duration_months integer,
    location_type character varying(20) NOT NULL,
    compensation_type character varying(20) NOT NULL,
    compensation_details text,
    status character varying(20) NOT NULL DEFAULT 'open',
    views integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT (now()),
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT "PK_projects" PRIMARY KEY (id),
    CONSTRAINT "FK_projects_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_skills (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    skill_id integer NOT NULL,
    level character varying(50),
    years_experience numeric(18,2),
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    "SkillId1" integer,
    CONSTRAINT "PK_user_skills" PRIMARY KEY (id),
    CONSTRAINT "FK_user_skills_skills_SkillId1" FOREIGN KEY ("SkillId1") REFERENCES skills (id),
    CONSTRAINT "FK_user_skills_skills_skill_id" FOREIGN KEY (skill_id) REFERENCES skills (id) ON DELETE CASCADE,
    CONSTRAINT "FK_user_skills_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE "UserEducations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "SchoolName" text,
    "Major" text,
    "Degree" text,
    "StartYear" integer,
    "EndYear" integer,
    "Description" text,
    "CreatedAt" timestamp without time zone,
    CONSTRAINT "PK_UserEducations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserEducations_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE "UserExperiences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CompanyName" text,
    "Position" text,
    "StartDate" date,
    "EndDate" date,
    "IsCurrent" boolean,
    "Description" text,
    "CreatedAt" timestamp without time zone,
    CONSTRAINT "PK_UserExperiences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserExperiences_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE "CompanyLocations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "Address" text,
    "City" text,
    "Country" text,
    "IsHeadquarter" boolean,
    "CreatedAt" timestamp without time zone,
    CONSTRAINT "PK_CompanyLocations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyLocations_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies ("Id") ON DELETE CASCADE
);

CREATE TABLE "CompanyVerifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "VerifiedBy" integer,
    "DocumentType" text,
    "DocumentUrl" text,
    "Status" text,
    "Notes" text,
    "SubmittedAt" timestamp without time zone,
    "VerifiedAt" timestamp without time zone,
    "VerifiedByNavigationId" integer,
    CONSTRAINT "PK_CompanyVerifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyVerifications_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CompanyVerifications_users_VerifiedByNavigationId" FOREIGN KEY ("VerifiedByNavigationId") REFERENCES users (id)
);

CREATE TABLE jobs (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Requirements" text,
    "Benefits" text,
    "Type" text,
    "Level" text,
    "SalaryMin" integer,
    "SalaryMax" integer,
    salary_currency character varying(10) DEFAULT 'VND',
    "Location" text,
    "LocationType" text,
    "Positions" integer,
    "Deadline" date,
    status character varying(20) DEFAULT 'open',
    "Views" integer,
    created_at timestamp without time zone DEFAULT (now()),
    updated_at timestamp without time zone DEFAULT (now()),
    CONSTRAINT "PK_jobs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_jobs_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "DurationMinutes" integer,
    "PassingScore" integer,
    "Status" text,
    "CreatedAt" timestamp without time zone,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Tests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tests_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies ("Id") ON DELETE CASCADE
);

CREATE TABLE project_positions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    project_id integer NOT NULL,
    role character varying(100) NOT NULL,
    quantity integer NOT NULL,
    requirements text,
    status character varying(20) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT "PK_project_positions" PRIMARY KEY (id),
    CONSTRAINT "FK_project_positions_projects_project_id" FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE TABLE applications (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "JobId" integer NOT NULL,
    "CoverLetter" text,
    "CvFile" text,
    status character varying(20) DEFAULT 'pending',
    "RejectReason" text,
    applied_at timestamp without time zone DEFAULT (now()),
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_applications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_applications_jobs_JobId" FOREIGN KEY ("JobId") REFERENCES jobs ("Id"),
    CONSTRAINT "FK_applications_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id)
);

CREATE TABLE "JobSkills" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "JobId" integer NOT NULL,
    "SkillId" integer NOT NULL,
    "IsRequired" boolean,
    "Level" text,
    CONSTRAINT "PK_JobSkills" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JobSkills_jobs_JobId" FOREIGN KEY ("JobId") REFERENCES jobs ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobSkills_skills_SkillId" FOREIGN KEY ("SkillId") REFERENCES skills (id) ON DELETE CASCADE
);

CREATE TABLE "SavedJobs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "JobId" integer NOT NULL,
    "CreatedAt" timestamp without time zone,
    CONSTRAINT "PK_SavedJobs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SavedJobs_jobs_JobId" FOREIGN KEY ("JobId") REFERENCES jobs ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SavedJobs_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE "JobTests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "JobId" integer NOT NULL,
    "TestId" integer NOT NULL,
    "IsRequired" boolean,
    CONSTRAINT "PK_JobTests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JobTests_Tests_TestId" FOREIGN KEY ("TestId") REFERENCES "Tests" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobTests_jobs_JobId" FOREIGN KEY ("JobId") REFERENCES jobs ("Id") ON DELETE CASCADE
);

CREATE TABLE "TestQuestions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TestId" integer NOT NULL,
    "Question" text NOT NULL,
    "Type" text,
    "Options" text,
    "CorrectAnswer" text,
    "Points" integer,
    "OrderNum" integer,
    CONSTRAINT "PK_TestQuestions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestQuestions_Tests_TestId" FOREIGN KEY ("TestId") REFERENCES "Tests" ("Id") ON DELETE CASCADE
);

CREATE TABLE project_applications (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    project_id integer NOT NULL,
    position_id integer NOT NULL,
    user_id integer NOT NULL,
    cover_letter text NOT NULL,
    portfolio_link character varying(500),
    status character varying(20) NOT NULL,
    applied_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT "PK_project_applications" PRIMARY KEY (id),
    CONSTRAINT "FK_project_applications_project_positions_position_id" FOREIGN KEY (position_id) REFERENCES project_positions (id) ON DELETE CASCADE,
    CONSTRAINT "FK_project_applications_projects_project_id" FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT "FK_project_applications_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE project_members (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    project_id integer NOT NULL,
    user_id integer NOT NULL,
    position_id integer,
    role_type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    joined_at date NOT NULL,
    left_at date,
    CONSTRAINT "PK_project_members" PRIMARY KEY (id),
    CONSTRAINT "FK_project_members_project_positions_position_id" FOREIGN KEY (position_id) REFERENCES project_positions (id),
    CONSTRAINT "FK_project_members_projects_project_id" FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT "FK_project_members_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE project_position_skills (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    position_id integer NOT NULL,
    skill_id integer NOT NULL,
    is_required boolean NOT NULL,
    "SkillId1" integer,
    CONSTRAINT "PK_project_position_skills" PRIMARY KEY (id),
    CONSTRAINT "FK_project_position_skills_project_positions_position_id" FOREIGN KEY (position_id) REFERENCES project_positions (id) ON DELETE CASCADE,
    CONSTRAINT "FK_project_position_skills_skills_SkillId1" FOREIGN KEY ("SkillId1") REFERENCES skills (id),
    CONSTRAINT "FK_project_position_skills_skills_skill_id" FOREIGN KEY (skill_id) REFERENCES skills (id) ON DELETE CASCADE
);

CREATE TABLE "ApplicationTests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ApplicationId" integer NOT NULL,
    "TestId" integer NOT NULL,
    "Answers" text,
    "Score" integer,
    "Status" text,
    "StartedAt" timestamp without time zone,
    "CompletedAt" timestamp without time zone,
    "ManualScores" text,
    CONSTRAINT "PK_ApplicationTests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ApplicationTests_Tests_TestId" FOREIGN KEY ("TestId") REFERENCES "Tests" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ApplicationTests_applications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES applications ("Id") ON DELETE CASCADE
);

CREATE TABLE "Interviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ApplicationId" integer NOT NULL,
    "Title" text,
    "Description" text,
    "ScheduledAt" timestamp without time zone NOT NULL,
    "DurationMinutes" integer,
    "MeetingLink" text,
    "Status" text,
    "Feedback" text,
    "CreatedAt" timestamp without time zone,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Interviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Interviews_applications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES applications ("Id") ON DELETE CASCADE
);

CREATE TABLE reviews (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FromUserId" integer NOT NULL,
    "ToUserId" integer NOT NULL,
    "ApplicationId" integer,
    "ProjectMemberId" integer,
    "Type" text,
    "Rating" integer NOT NULL,
    "Comment" text,
    "IsVisible" boolean,
    "CreatedAt" timestamp without time zone,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_reviews_applications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES applications ("Id"),
    CONSTRAINT "FK_reviews_project_members_ProjectMemberId" FOREIGN KEY ("ProjectMemberId") REFERENCES project_members (id),
    CONSTRAINT "FK_reviews_users_FromUserId" FOREIGN KEY ("FromUserId") REFERENCES users (id),
    CONSTRAINT "FK_reviews_users_ToUserId" FOREIGN KEY ("ToUserId") REFERENCES users (id)
);

CREATE TABLE "Reports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReporterId" integer NOT NULL,
    "Type" text,
    "ReportedUserId" integer,
    "ReportedJobId" integer,
    "ReportedReviewId" integer,
    "ReportedProjectId" integer,
    "Reason" text NOT NULL,
    "Status" text,
    "HandledBy" integer,
    "AdminNote" text,
    "CreatedAt" timestamp without time zone,
    "ResolvedAt" timestamp without time zone,
    CONSTRAINT "PK_Reports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reports_jobs_ReportedJobId" FOREIGN KEY ("ReportedJobId") REFERENCES jobs ("Id"),
    CONSTRAINT "FK_Reports_projects_ReportedProjectId" FOREIGN KEY ("ReportedProjectId") REFERENCES projects (id),
    CONSTRAINT "FK_Reports_reviews_ReportedReviewId" FOREIGN KEY ("ReportedReviewId") REFERENCES reviews ("Id")
);

CREATE INDEX "IX_AdminLogs_AdminId" ON "AdminLogs" ("AdminId");

CREATE INDEX "IX_applications_JobId" ON applications ("JobId");

CREATE INDEX "IX_applications_UserId" ON applications ("UserId");

CREATE INDEX "IX_ApplicationTests_ApplicationId" ON "ApplicationTests" ("ApplicationId");

CREATE INDEX "IX_ApplicationTests_TestId" ON "ApplicationTests" ("TestId");

CREATE UNIQUE INDEX "IX_companies_UserId" ON companies ("UserId");

CREATE INDEX "IX_CompanyLocations_CompanyId" ON "CompanyLocations" ("CompanyId");

CREATE INDEX "IX_CompanyVerifications_CompanyId" ON "CompanyVerifications" ("CompanyId");

CREATE INDEX "IX_CompanyVerifications_VerifiedByNavigationId" ON "CompanyVerifications" ("VerifiedByNavigationId");

CREATE INDEX "IX_Interviews_ApplicationId" ON "Interviews" ("ApplicationId");

CREATE INDEX "IX_jobs_CompanyId" ON jobs ("CompanyId");

CREATE INDEX "IX_JobSkills_JobId" ON "JobSkills" ("JobId");

CREATE INDEX "IX_JobSkills_SkillId" ON "JobSkills" ("SkillId");

CREATE INDEX "IX_JobTests_JobId" ON "JobTests" ("JobId");

CREATE INDEX "IX_JobTests_TestId" ON "JobTests" ("TestId");

CREATE INDEX "IX_messages_FromUserId" ON messages ("FromUserId");

CREATE INDEX "IX_messages_ToUserId" ON messages ("ToUserId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_project_applications_position_id" ON project_applications (position_id);

CREATE INDEX "IX_project_applications_project_id" ON project_applications (project_id);

CREATE INDEX "IX_project_applications_user_id" ON project_applications (user_id);

CREATE INDEX "IX_project_members_position_id" ON project_members (position_id);

CREATE INDEX "IX_project_members_project_id" ON project_members (project_id);

CREATE INDEX "IX_project_members_user_id" ON project_members (user_id);

CREATE INDEX "IX_project_position_skills_position_id" ON project_position_skills (position_id);

CREATE INDEX "IX_project_position_skills_skill_id" ON project_position_skills (skill_id);

CREATE INDEX "IX_project_position_skills_SkillId1" ON project_position_skills ("SkillId1");

CREATE INDEX "IX_project_positions_project_id" ON project_positions (project_id);

CREATE INDEX "IX_projects_user_id" ON projects (user_id);

CREATE INDEX "IX_Reports_ReportedJobId" ON "Reports" ("ReportedJobId");

CREATE INDEX "IX_Reports_ReportedProjectId" ON "Reports" ("ReportedProjectId");

CREATE INDEX "IX_Reports_ReportedReviewId" ON "Reports" ("ReportedReviewId");

CREATE INDEX "IX_reviews_ApplicationId" ON reviews ("ApplicationId");

CREATE INDEX "IX_reviews_FromUserId" ON reviews ("FromUserId");

CREATE INDEX "IX_reviews_ProjectMemberId" ON reviews ("ProjectMemberId");

CREATE INDEX "IX_reviews_ToUserId" ON reviews ("ToUserId");

CREATE INDEX "IX_SavedJobs_JobId" ON "SavedJobs" ("JobId");

CREATE INDEX "IX_SavedJobs_UserId" ON "SavedJobs" ("UserId");

CREATE INDEX "IX_TestQuestions_TestId" ON "TestQuestions" ("TestId");

CREATE INDEX "IX_Tests_CompanyId" ON "Tests" ("CompanyId");

CREATE INDEX "IX_user_skills_skill_id" ON user_skills (skill_id);

CREATE INDEX "IX_user_skills_SkillId1" ON user_skills ("SkillId1");

CREATE INDEX "IX_user_skills_user_id" ON user_skills (user_id);

CREATE INDEX "IX_UserEducations_UserId" ON "UserEducations" ("UserId");

CREATE INDEX "IX_UserExperiences_UserId" ON "UserExperiences" ("UserId");

CREATE INDEX idx_users_email ON users (email);

CREATE INDEX idx_users_role ON users (role);

CREATE INDEX idx_users_status ON users (status);

CREATE UNIQUE INDEX "IX_users_email" ON users (email);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260403094052_InitialCreate', '9.0.9');

COMMIT;

